### ISSUE TITLE
SynchronizedDispatcher cannot use WinForms application's SynchronizationContext

### ISSUE THREAD

**Issue by sadesyllas** [akkadotnet/getakka.net#184]
- Winows 10
- Visual Studio 2015 Enterprise
- Akka 1.1.0

While running the https://github.com/petabridge/akka-bootcamp, lessons 2 and 3 (`.NET 4.6` - `WinForms` applications that want to use `Akka.net` `SynchronizedDispatcher` so as to access UI controls in the UI thread), I get this error when using the SynchronizedDispatcher through the following configuration):
#### Configuration

``` javascript
akka {
    actor{
        serializers {
            wire = "Akka.Serialization.WireSerializer, Akka.Serialization.Wire"
        }
        serialization-bindins {
            "System.Object" = 
        }
        deployment{
            /mainform{
                dispatcher = akka.actor.synchronized-dispatcher
            }
            /authenticator{
                dispatcher = akka.actor.synchronized-dispatcher 
            }
        }
    }
}
```
#### Error

```
[ERROR][15-Jul-16 08:40:37][Thread 0012][LocalActorRefProvider(akka://GithubActors)] Guardian failed. Shutting down system
Cause: System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()
   at Akka.Dispatch.CurrentSynchronizationContextExecutorServiceFactory.Produce(String id)
   at Akka.Dispatch.Dispatcher.LazyExecutorServiceDelegate.<>c__DisplayClass3_0.<.ctor>b__0()
   at Akka.Util.FastLazy`1.get_Value()
   at Akka.Dispatch.Dispatcher.LazyExecutorServiceDelegate.get_Executor()
   at Akka.Dispatch.Dispatcher.get_Executor()
   at Akka.Dispatch.Dispatcher.ExecuteTask(IRunnable run)
   at Akka.Dispatch.MessageDispatcher.RegisterForExecution(Mailbox mbox, Boolean hasMessageHint, Boolean hasSystemMessageHint)
   at Akka.Dispatch.MessageDispatcher.Attach(ActorCell cell)
   at Akka.Actor.ActorCell.Start()
   at Akka.Actor.RepointableActorRef.Point()
   at Akka.Actor.ActorCell.HandleSupervise(IActorRef child, Boolean async)
   at Akka.Actor.ActorCell.Supervise(IActorRef child, Boolean async)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
[ERROR][15-Jul-16 08:40:37][Thread 0012][akka://GithubActors/user] The current SynchronizationContext may not be used as a TaskScheduler.
Cause: System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()
   at Akka.Dispatch.CurrentSynchronizationContextExecutorServiceFactory.Produce(String id)
   at Akka.Dispatch.Dispatcher.LazyExecutorServiceDelegate.<>c__DisplayClass3_0.<.ctor>b__0()
   at Akka.Util.FastLazy`1.get_Value()
   at Akka.Dispatch.Dispatcher.LazyExecutorServiceDelegate.get_Executor()
   at Akka.Dispatch.Dispatcher.get_Executor()
   at Akka.Dispatch.Dispatcher.ExecuteTask(IRunnable run)
   at Akka.Dispatch.MessageDispatcher.RegisterForExecution(Mailbox mbox, Boolean hasMessageHint, Boolean hasSystemMessageHint)
   at Akka.Dispatch.MessageDispatcher.Attach(ActorCell cell)
   at Akka.Actor.ActorCell.Start()
   at Akka.Actor.RepointableActorRef.Point()
   at Akka.Actor.ActorCell.HandleSupervise(IActorRef child, Boolean async)
   at Akka.Actor.ActorCell.Supervise(IActorRef child, Boolean async)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)
```

**Comment by Aaronontheweb** [comment]
Already reported and fixed. Going out in 1.1.1

**Comment by sadesyllas** [comment]
@Aaronontheweb, thanks for the quick reply. :+1:  Akka.net is a great framework! Keep up the good work.
